# Copyright 2019 SiFive, Inc #
# SPDX-License-Identifier: Apache-2.0 #

# C:\VSD_Sqd_Project\sifive_hifive1_BitNet_MNIST_App\src\Makefile

# Copyright 2019 SiFive, Inc #
# SPDX-License-Identifier: Apache-2.0 #

PROGRAM ?= main

$(PROGRAM): $(wildcard *.c) $(wildcard *.h) $(wildcard *.S) mnist_model_params.c

clean:
	rm -f $(PROGRAM) $(PROGRAM).hex

