/*
 * This file is auto-generated by generate_c_model_params.py.
 * Do not modify manually.
 */
#ifndef MNIST_MODEL_PARAMS_H
#define MNIST_MODEL_PARAMS_H

#include <stdint.h>

#define MAX_N_ACTIVATIONS 64
#define INPUT_SCALE_FACTOR 64
#define ACTIVATION_BITS 8
#define BATCH_SIZE 16

// Add buffer overflow protection
#define SAFE_ACCESS(arr, idx, max) ((idx) < (max) ? arr[idx] : 0)

// Add memory alignment for better performance
#define ALIGN_16 __attribute__((aligned(16)))

// Layer 1 Parameters
extern const uint32_t ALIGN_16 L1_weights[6272];
extern const int32_t ALIGN_16 L1_biases[32];
extern const int32_t L1_bitperweight;
extern const uint32_t L1_incoming_weights;
extern const uint32_t L1_outgoing_weights;
extern const float L1_input_scale;
extern const int32_t L1_input_zero_point;
extern const float L1_output_scale;
extern const int32_t L1_output_zero_point;
extern const float L1_weights_scale;
extern const int32_t L1_weights_zero_point;

// Layer 2 Parameters
extern const uint32_t ALIGN_16 L2_weights[128];
extern const int32_t ALIGN_16 L2_biases[16];
extern const int32_t L2_bitperweight;
extern const uint32_t L2_incoming_weights;
extern const uint32_t L2_outgoing_weights;
extern const float L2_input_scale;
extern const int32_t L2_input_zero_point;
extern const float L2_output_scale;
extern const int32_t L2_output_zero_point;
extern const float L2_weights_scale;
extern const int32_t L2_weights_zero_point;

// Layer 3 Parameters
extern const uint32_t ALIGN_16 L3_weights[40];
extern const int32_t ALIGN_16 L3_biases[10];
extern const int32_t L3_bitperweight;
extern const uint32_t L3_incoming_weights;
extern const uint32_t L3_outgoing_weights;
extern const float L3_input_scale;
extern const int32_t L3_input_zero_point;
extern const float L3_output_scale;
extern const int32_t L3_output_zero_point;
extern const float L3_weights_scale;
extern const int32_t L3_weights_zero_point;

// Quantized sample input images and their labels
extern const int8_t input_data_0[784];
extern const uint8_t label_0;
extern const int8_t input_data_1[784];
extern const uint8_t label_1;
extern const int8_t input_data_2[784];
extern const uint8_t label_2;
extern const int8_t input_data_3[784];
extern const uint8_t label_3;
extern const int8_t input_data_4[784];
extern const uint8_t label_4;
extern const int8_t input_data_5[784];
extern const uint8_t label_5;
extern const int8_t input_data_6[784];
extern const uint8_t label_6;
extern const int8_t input_data_7[784];
extern const uint8_t label_7;
extern const int8_t input_data_8[784];
extern const uint8_t label_8;
extern const int8_t input_data_9[784];
extern const uint8_t label_9;

#endif // MNIST_MODEL_PARAMS_H
