/*
 * This file is auto-generated by generate_c_model_params.py.
 * Do not modify manually.
 */
#ifndef MNIST_MODEL_PARAMS_H
#define MNIST_MODEL_PARAMS_H

#include <stdint.h>

#define MAX_N_ACTIVATIONS 64

// Layer 1 Parameters
extern const uint32_t L1_weights[1568];
extern const int32_t L1_biases[8];
extern const int32_t L1_bitperweight;
extern const uint32_t L1_incoming_weights;
extern const uint32_t L1_outgoing_weights;
extern const float L1_input_scale;
extern const int32_t L1_input_zero_point;
extern const float L1_output_scale;
extern const int32_t L1_output_zero_point;
extern const float L1_weights_scale;
extern const int32_t L1_weights_zero_point;

// Layer 2 Parameters
extern const uint32_t L2_weights[20];
extern const int32_t L2_biases[10];
extern const int32_t L2_bitperweight;
extern const uint32_t L2_incoming_weights;
extern const uint32_t L2_outgoing_weights;
extern const float L2_input_scale;
extern const int32_t L2_input_zero_point;
extern const float L2_output_scale;
extern const int32_t L2_output_zero_point;
extern const float L2_weights_scale;
extern const int32_t L2_weights_zero_point;

// Quantized sample input images and their labels
extern const int8_t input_data_0[784];
extern const uint8_t label_0;
extern const int8_t input_data_1[784];
extern const uint8_t label_1;
extern const int8_t input_data_2[784];
extern const uint8_t label_2;
extern const int8_t input_data_3[784];
extern const uint8_t label_3;

#endif // MNIST_MODEL_PARAMS_H
